//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace PPSI.Web.Pupuk
{
	/// <summary>
	/// Database       : pupuk_ppsi
	/// Data Source    : 127.0.0.1
	/// Server Version : 5.5.5-10.1.16-MariaDB
	/// </summary>
	public partial class pupuk_ppsi : LinqToDB.Data.DataConnection
	{
		public ITable<Billing>                    Billings                   { get { return this.GetTable<Billing>(); } }
		public ITable<GrnDetails>                 GrnDetails                 { get { return this.GetTable<GrnDetails>(); } }
		public ITable<GrnHeader>                  GrnHeader                  { get { return this.GetTable<GrnHeader>(); } }
		public ITable<MsAktor>                    MsAktor                    { get { return this.GetTable<MsAktor>(); } }
		public ITable<MsPupuk>                    MsPupuk                    { get { return this.GetTable<MsPupuk>(); } }
		public ITable<Payment>                    Payments                   { get { return this.GetTable<Payment>(); } }
		public ITable<PupukStocks>                PupukStocks                { get { return this.GetTable<PupukStocks>(); } }
		public ITable<PupukStores>                PupukStores                { get { return this.GetTable<PupukStores>(); } }
		public ITable<PurchaseOrderDetails>       PurchaseOrderDetails       { get { return this.GetTable<PurchaseOrderDetails>(); } }
		public ITable<PurchaseOrders>             PurchaseOrders             { get { return this.GetTable<PurchaseOrders>(); } }
		public ITable<PurchaseRequisition>        PurchaseRequisition        { get { return this.GetTable<PurchaseRequisition>(); } }
		public ITable<PurchaseRequisitionDetails> PurchaseRequisitionDetails { get { return this.GetTable<PurchaseRequisitionDetails>(); } }
		public ITable<Refarea>                    Refareas                   { get { return this.GetTable<Refarea>(); } }
		public ITable<Refkota>                    Refkotas                   { get { return this.GetTable<Refkota>(); } }
		public ITable<Refnegara>                  Refnegaras                 { get { return this.GetTable<Refnegara>(); } }
		public ITable<Refprovinsi>                Refprovinsis               { get { return this.GetTable<Refprovinsi>(); } }
		public ITable<Role>                       Roles                      { get { return this.GetTable<Role>(); } }
		public ITable<SequenceNumbers>            SequenceNumbers            { get { return this.GetTable<SequenceNumbers>(); } }
		public ITable<StaticData>                 StaticData                 { get { return this.GetTable<StaticData>(); } }
		public ITable<Store>                      Stores                     { get { return this.GetTable<Store>(); } }
		public ITable<Transaction>                Transactions               { get { return this.GetTable<Transaction>(); } }
		public ITable<TransactionBillRels>        TransactionBillRels        { get { return this.GetTable<TransactionBillRels>(); } }
		public ITable<User>                       Users                      { get { return this.GetTable<User>(); } }
		public ITable<Vlogin>                     Vlogins                    { get { return this.GetTable<Vlogin>(); } }

		public pupuk_ppsi()
		{
			InitDataContext();
		}

		public pupuk_ppsi(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("billings")]
	public partial class Billing
	{
		[Column(@"billing_id"),   PrimaryKey,  Identity] public int       BillingId   { get; set; } // int(11)
		[Column(@"kode"),            Nullable          ] public string    Kode        { get; set; } // varchar(15)
		[Column(@"discount"),        Nullable          ] public decimal?  Discount    { get; set; } // decimal(18,2)
		[Column(@"total_amount"),    Nullable          ] public decimal?  TotalAmount { get; set; } // decimal(18,2)
		[Column(@"round_amount"),    Nullable          ] public decimal?  RoundAmount { get; set; } // decimal(18,2)
		[Column(@"bill_date"),       Nullable          ] public DateTime? BillDate    { get; set; } // date
		[Column(@"is_delete"),    NotNull              ] public ulong     IsDelete    { get; set; } // bit(1)
		[Column(@"add_date"),        Nullable          ] public DateTime? AddDate     { get; set; } // datetime
		[Column(@"add_by"),          Nullable          ] public string    AddBy       { get; set; } // varchar(100)
		[Column(@"edit_date"),       Nullable          ] public DateTime? EditDate    { get; set; } // datetime
		[Column(@"edit_by"),         Nullable          ] public string    EditBy      { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_payments_billings_billing_id_BackReference
		/// </summary>
		[Association(ThisKey="BillingId", OtherKey="BillingId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Payment> paymentsbillingids { get; set; }

		/// <summary>
		/// FK_transaction_bill_rels_billings_billing_id_BackReference
		/// </summary>
		[Association(ThisKey="BillingId", OtherKey="BillingId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<TransactionBillRels> transactionbillrelsbillingids { get; set; }

		#endregion
	}

	[Table("grn_details")]
	public partial class GrnDetails
	{
		[Column(@"grn_detail_id"), PrimaryKey,  Identity] public int       GrnDetailId { get; set; } // int(11)
		[Column(@"grn_header_id"), NotNull              ] public int       GrnHeaderId { get; set; } // int(11)
		[Column(@"pupuk_id"),      NotNull              ] public int       PupukId     { get; set; } // int(11)
		[Column(@"produsen_id"),      Nullable          ] public int?      ProdusenId  { get; set; } // int(11)
		[Column(@"qty"),              Nullable          ] public int?      Qty         { get; set; } // int(11)
		[Column(@"description"),      Nullable          ] public string    Description { get; set; } // varchar(255)
		[Column(@"expired_date"),     Nullable          ] public DateTime? ExpiredDate { get; set; } // date
		[Column(@"sale_price"),       Nullable          ] public decimal?  SalePrice   { get; set; } // decimal(18,2)
		[Column(@"add_date"),         Nullable          ] public DateTime? AddDate     { get; set; } // datetime
		[Column(@"add_by"),           Nullable          ] public string    AddBy       { get; set; } // varchar(100)
		[Column(@"edit_date"),        Nullable          ] public DateTime? EditDate    { get; set; } // datetime
		[Column(@"edit_by"),          Nullable          ] public string    EditBy      { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_grn_details_grn_header_id
		/// </summary>
		[Association(ThisKey="GrnHeaderId", OtherKey="GrnHeaderId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_grn_details_grn_header_id", BackReferenceName="grndetailsgrnheaderids")]
		public GrnHeader grndetailsgrnheaderid { get; set; }

		/// <summary>
		/// FK_grn_details_ms_aktor_aktor_id
		/// </summary>
		[Association(ThisKey="ProdusenId", OtherKey="AktorId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_grn_details_ms_aktor_aktor_id", BackReferenceName="grndetailsmsaktoraktorids")]
		public MsAktor grndetailsmsaktoraktorid { get; set; }

		/// <summary>
		/// FK_grn_details_ms_pupuk_pupuk_id
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_grn_details_ms_pupuk_pupuk_id", BackReferenceName="grndetailsmspupukpupukids")]
		public MsPupuk grndetailsmspupukpupukid { get; set; }

		#endregion
	}

	[Table("grn_header")]
	public partial class GrnHeader
	{
		[Column(@"grn_header_id"),      PrimaryKey, Identity] public int       GrnHeaderId      { get; set; } // int(11)
		[Column(@"kode"),               Nullable            ] public string    Kode             { get; set; } // varchar(15)
		[Column(@"po_id"),              Nullable            ] public int?      PoId             { get; set; } // int(11)
		[Column(@"grn_date"),           Nullable            ] public DateTime? GrnDate          { get; set; } // date
		[Column(@"store_id"),           Nullable            ] public int?      StoreId          { get; set; } // int(11)
		[Column(@"note"),               Nullable            ] public string    Note             { get; set; } // varchar(255)
		[Column(@"document_status_id"), Nullable            ] public int?      DocumentStatusId { get; set; } // int(11)
		[Column(@"receive_by"),         Nullable            ] public string    ReceiveBy        { get; set; } // varchar(100)
		[Column(@"add_date"),           Nullable            ] public DateTime? AddDate          { get; set; } // datetime
		[Column(@"add_by"),             Nullable            ] public string    AddBy            { get; set; } // varchar(100)
		[Column(@"edit_date"),          Nullable            ] public DateTime? EditDate         { get; set; } // datetime
		[Column(@"edit_by"),            Nullable            ] public string    EditBy           { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_grn_details_grn_header_id_BackReference
		/// </summary>
		[Association(ThisKey="GrnHeaderId", OtherKey="GrnHeaderId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<GrnDetails> grndetailsgrnheaderids { get; set; }

		/// <summary>
		/// FK_grn_header_po_id
		/// </summary>
		[Association(ThisKey="PoId", OtherKey="PurchaseOrderId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_grn_header_po_id", BackReferenceName="grnheaderpoids")]
		public PurchaseOrders grnheaderpoid { get; set; }

		#endregion
	}

	[Table("ms_aktor")]
	public partial class MsAktor
	{
		[Column(@"aktor_id"),        PrimaryKey,  Identity] public int       AktorId        { get; set; } // int(11)
		[Column(@"role_id"),         NotNull              ] public int       RoleId         { get; set; } // int(11)
		[Column(@"kode"),               Nullable          ] public string    Kode           { get; set; } // varchar(15)
		[Column(@"nama"),               Nullable          ] public string    Nama           { get; set; } // varchar(100)
		[Column(@"alamat"),             Nullable          ] public string    Alamat         { get; set; } // varchar(255)
		[Column(@"provinsi_id"),        Nullable          ] public int?      ProvinsiId     { get; set; } // int(11)
		[Column(@"kabupaten_id"),       Nullable          ] public int?      KabupatenId    { get; set; } // int(11)
		[Column(@"kecamatan_id"),       Nullable          ] public int?      KecamatanId    { get; set; } // int(11)
		[Column(@"kode_pos"),           Nullable          ] public string    KodePos        { get; set; } // varchar(10)
		[Column(@"nomor_handphone"),    Nullable          ] public string    NomorHandphone { get; set; } // varchar(13)
		[Column(@"email"),              Nullable          ] public string    Email          { get; set; } // varchar(100)
		[Column(@"is_delete"),       NotNull              ] public ulong     IsDelete       { get; set; } // bit(1)
		[Column(@"add_date"),           Nullable          ] public DateTime? AddDate        { get; set; } // datetime
		[Column(@"add_by"),             Nullable          ] public string    AddBy          { get; set; } // varchar(100)
		[Column(@"edit_date"),          Nullable          ] public DateTime? EditDate       { get; set; } // datetime
		[Column(@"edit_by"),            Nullable          ] public string    EditBy         { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_grn_details_ms_aktor_aktor_id_BackReference
		/// </summary>
		[Association(ThisKey="AktorId", OtherKey="ProdusenId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<GrnDetails> grndetailsmsaktoraktorids { get; set; }

		/// <summary>
		/// FK_ms_aktor_role_role_id
		/// </summary>
		[Association(ThisKey="RoleId", OtherKey="RoleId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_ms_aktor_role_role_id", BackReferenceName="msaktorids")]
		public Role msaktorroleroleid { get; set; }

		/// <summary>
		/// FK_po_ms_aktor_aktor_id_BackReference
		/// </summary>
		[Association(ThisKey="AktorId", OtherKey="ProdusenId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PurchaseOrders> pomsaktoraktorids { get; set; }

		/// <summary>
		/// FK_purchase_requisition_ms_aktor_aktor_id_BackReference
		/// </summary>
		[Association(ThisKey="AktorId", OtherKey="AktorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PurchaseRequisition> purchaserequisitionmsaktoraktorids { get; set; }

		/// <summary>
		/// FK_stores_ms_aktor_aktor_id_BackReference
		/// </summary>
		[Association(ThisKey="AktorId", OtherKey="DistributorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Store> storesmsaktoraktorids { get; set; }

		/// <summary>
		/// FK_transactions_ms_aktor_aktor_id_BackReference
		/// </summary>
		[Association(ThisKey="AktorId", OtherKey="PetaniId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Transaction> transactionsmsaktoraktorids { get; set; }

		/// <summary>
		/// FK_users_ms_aktor_aktor_id_BackReference
		/// </summary>
		[Association(ThisKey="AktorId", OtherKey="AktorId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<User> usersmsaktoraktorids { get; set; }

		#endregion
	}

	[Table("ms_pupuk")]
	public partial class MsPupuk
	{
		[Column(@"pupuk_id"),          PrimaryKey,  Identity] public int       PupukId         { get; set; } // int(11)
		[Column(@"kode"),                 Nullable          ] public string    Kode            { get; set; } // varchar(15)
		[Column(@"nama"),                 Nullable          ] public string    Nama            { get; set; } // varchar(100)
		[Column(@"base_price"),        NotNull              ] public decimal   BasePrice       { get; set; } // decimal(18,2)
		[Column(@"sumber_pupuk_id"),      Nullable          ] public int?      SumberPupukId   { get; set; } // int(11)
		[Column(@"jenis_unsur_id"),       Nullable          ] public int?      JenisUnsurId    { get; set; } // int(11)
		[Column(@"bentuk_pupuk_id"),      Nullable          ] public int?      BentukPupukId   { get; set; } // int(11)
		[Column(@"cara_pakai_id"),        Nullable          ] public int?      CaraPakaiId     { get; set; } // int(11)
		[Column(@"cara_pelepasan_id"),    Nullable          ] public int?      CaraPelepasanId { get; set; } // int(11)
		[Column(@"komposisi"),            Nullable          ] public string    Komposisi       { get; set; } // varchar(500)
		[Column(@"gambar"),               Nullable          ] public string    Gambar          { get; set; } // varchar(255)
		[Column(@"is_delete"),         NotNull              ] public ulong     IsDelete        { get; set; } // bit(1)
		[Column(@"add_date"),             Nullable          ] public DateTime? AddDate         { get; set; } // datetime
		[Column(@"add_by"),               Nullable          ] public string    AddBy           { get; set; } // varchar(100)
		[Column(@"edit_date"),            Nullable          ] public DateTime? EditDate        { get; set; } // datetime
		[Column(@"edit_by"),              Nullable          ] public string    EditBy          { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_grn_details_ms_pupuk_pupuk_id_BackReference
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<GrnDetails> grndetailsmspupukpupukids { get; set; }

		/// <summary>
		/// FK_ms_pupuk_carapelepasan_staticdata
		/// </summary>
		[Association(ThisKey="CaraPelepasanId", OtherKey="StaticDataId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_ms_pupuk_carapelepasan_staticdata", BackReferenceName="mspupukcarapelepasanstaticdatas")]
		public StaticData mspupukcarapelepasanstaticdata { get; set; }

		/// <summary>
		/// FK_ms_pupuk_static_data_bentuk_pupuk_id
		/// </summary>
		[Association(ThisKey="BentukPupukId", OtherKey="StaticDataId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_ms_pupuk_static_data_bentuk_pupuk_id", BackReferenceName="mspupukstaticdatabentukpupukids")]
		public StaticData mspupukstaticdatabentukpupukid { get; set; }

		/// <summary>
		/// FK_ms_pupuk_static_data_cara_pakai_id
		/// </summary>
		[Association(ThisKey="CaraPakaiId", OtherKey="StaticDataId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_ms_pupuk_static_data_cara_pakai_id", BackReferenceName="mspupukstaticdatacarapakaiids")]
		public StaticData mspupukstaticdatacarapakaiid { get; set; }

		/// <summary>
		/// FK_ms_pupuk_static_data_jenis_unsur_id
		/// </summary>
		[Association(ThisKey="JenisUnsurId", OtherKey="StaticDataId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_ms_pupuk_static_data_jenis_unsur_id", BackReferenceName="mspupukstaticdatajenisunsurids")]
		public StaticData mspupukstaticdatajenisunsurid { get; set; }

		/// <summary>
		/// FK_ms_pupuk_static_data_sumber_pupuk_id
		/// </summary>
		[Association(ThisKey="SumberPupukId", OtherKey="StaticDataId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_ms_pupuk_static_data_sumber_pupuk_id", BackReferenceName="mspupukstaticdatasumberpupukids")]
		public StaticData mspupukstaticdatasumberpupukid { get; set; }

		/// <summary>
		/// FK_po_details_ms_pupuk_pupuk_id_BackReference
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PurchaseOrderDetails> podetailsmspupukpupukids { get; set; }

		/// <summary>
		/// FK_pr_details_ms_pupuk_pupuk_id_BackReference
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PurchaseRequisitionDetails> prdetailsmspupukpupukids { get; set; }

		/// <summary>
		/// FK_pupuk_stores_ms_pupuk_pupuk_id_BackReference
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PupukStores> pupukstoresmspupukpupukids { get; set; }

		/// <summary>
		/// FK_transactions_ms_pupuk_pupuk_id_BackReference
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Transaction> transactionsmspupukpupukids { get; set; }

		#endregion
	}

	[Table("payments")]
	public partial class Payment
	{
		[Column(@"payment_id"),      PrimaryKey,  Identity] public int       PaymentId      { get; set; } // int(11)
		[Column(@"billing_id"),         Nullable          ] public int?      BillingId      { get; set; } // int(11)
		[Column(@"paid"),            NotNull              ] public decimal   Paid           { get; set; } // decimal(18,2)
		[Column(@"discount"),        NotNull              ] public decimal   Discount       { get; set; } // decimal(18,2)
		[Column(@"discount_amount"), NotNull              ] public decimal   DiscountAmount { get; set; } // decimal(18,2)
		[Column(@"is_delete"),       NotNull              ] public ulong     IsDelete       { get; set; } // bit(1)
		[Column(@"add_date"),           Nullable          ] public DateTime? AddDate        { get; set; } // datetime
		[Column(@"add_by"),             Nullable          ] public string    AddBy          { get; set; } // varchar(100)
		[Column(@"edit_date"),          Nullable          ] public DateTime? EditDate       { get; set; } // datetime
		[Column(@"edit_by"),            Nullable          ] public string    EditBy         { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_payments_billings_billing_id
		/// </summary>
		[Association(ThisKey="BillingId", OtherKey="BillingId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_payments_billings_billing_id", BackReferenceName="paymentsbillingids")]
		public Billing billingsbillingid { get; set; }

		#endregion
	}

	[Table("pupuk_stocks")]
	public partial class PupukStocks
	{
		[Column(@"pupuk_stock_id"),   PrimaryKey, Identity] public int       PupukStockId    { get; set; } // int(11)
		[Column(@"pupuk_store_id"),   Nullable            ] public int?      PupukStoreId    { get; set; } // int(11)
		[Column(@"out_value"),        Nullable            ] public int?      OutValue        { get; set; } // int(11)
		[Column(@"in_value"),         Nullable            ] public int?      InValue         { get; set; } // int(11)
		[Column(@"begining_saldo"),   Nullable            ] public int?      BeginingSaldo   { get; set; } // int(11)
		[Column(@"ref_code"),         Nullable            ] public string    RefCode         { get; set; } // varchar(50)
		[Column(@"transaction_time"), Nullable            ] public DateTime? TransactionTime { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_pupuk_stocks_pupuk_store_id
		/// </summary>
		[Association(ThisKey="PupukStoreId", OtherKey="PupukStoreId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_pupuk_stocks_pupuk_store_id", BackReferenceName="pupukstockspupukstoreids")]
		public PupukStores pupukstockspupukstoreid { get; set; }

		#endregion
	}

	[Table("pupuk_stores")]
	public partial class PupukStores
	{
		[Column(@"pupuk_store_id"),   PrimaryKey,  NotNull] public int       PupukStoreId    { get; set; } // int(11)
		[Column(@"pupuk_id"),            Nullable         ] public int?      PupukId         { get; set; } // int(11)
		[Column(@"store_id"),            Nullable         ] public int?      StoreId         { get; set; } // int(11)
		[Column(@"max_value"),           Nullable         ] public int?      MaxValue        { get; set; } // int(11)
		[Column(@"min_value"),           Nullable         ] public int?      MinValue        { get; set; } // int(11)
		[Column(@"is_auto_po"),                    NotNull] public ulong     IsAutoPo        { get; set; } // bit(1)
		[Column(@"soh"),                 Nullable         ] public string    Soh             { get; set; } // varchar(255)
		[Column(@"transaction_time"),    Nullable         ] public DateTime? TransactionTime { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_pupuk_stocks_pupuk_store_id_BackReference
		/// </summary>
		[Association(ThisKey="PupukStoreId", OtherKey="PupukStoreId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PupukStocks> pupukstockspupukstoreids { get; set; }

		/// <summary>
		/// FK_pupuk_stores_ms_pupuk_pupuk_id
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_pupuk_stores_ms_pupuk_pupuk_id", BackReferenceName="pupukstoresmspupukpupukids")]
		public MsPupuk pupukstoresmspupukpupukid { get; set; }

		/// <summary>
		/// FK_pupuk_stores_stores_store_id
		/// </summary>
		[Association(ThisKey="StoreId", OtherKey="StoreId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_pupuk_stores_stores_store_id", BackReferenceName="pupukstoreids")]
		public Store pupukstoresstoresstoreid { get; set; }

		#endregion
	}

	[Table("purchase_order_details")]
	public partial class PurchaseOrderDetails
	{
		[Column(@"po_details_id"), PrimaryKey,  Identity] public int       PoDetailsId { get; set; } // int(11)
		[Column(@"po_id"),         NotNull              ] public int       PoId        { get; set; } // int(11)
		[Column(@"pupuk_id"),      NotNull              ] public int       PupukId     { get; set; } // int(11)
		[Column(@"qty"),              Nullable          ] public int?      Qty         { get; set; } // int(11)
		[Column(@"sale_price"),       Nullable          ] public decimal?  SalePrice   { get; set; } // decimal(18,2)
		[Column(@"description"),      Nullable          ] public string    Description { get; set; } // varchar(255)
		[Column(@"add_date"),         Nullable          ] public DateTime? AddDate     { get; set; } // datetime
		[Column(@"add_by"),           Nullable          ] public string    AddBy       { get; set; } // varchar(100)
		[Column(@"edit_date"),        Nullable          ] public DateTime? EditDate    { get; set; } // datetime
		[Column(@"edit_by"),          Nullable          ] public string    EditBy      { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_po_details_ms_pupuk_pupuk_id
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_po_details_ms_pupuk_pupuk_id", BackReferenceName="podetailsmspupukpupukids")]
		public MsPupuk podetailsmspupukpupukid { get; set; }

		/// <summary>
		/// FK_po_details_po_purchase_order_id
		/// </summary>
		[Association(ThisKey="PoId", OtherKey="PurchaseOrderId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_po_details_po_purchase_order_id", BackReferenceName="podetailspopurchaseorderids")]
		public PurchaseOrders podetailspopurchaseorderid { get; set; }

		#endregion
	}

	[Table("purchase_orders")]
	public partial class PurchaseOrders
	{
		[Column(@"purchase_order_id"),  PrimaryKey, Identity] public int       PurchaseOrderId  { get; set; } // int(11)
		[Column(@"pr_id"),              Nullable            ] public int?      PrId             { get; set; } // int(11)
		[Column(@"produsen_id"),        Nullable            ] public int?      ProdusenId       { get; set; } // int(11)
		[Column(@"po_date"),            Nullable            ] public DateTime? PoDate           { get; set; } // date
		[Column(@"due_date"),           Nullable            ] public DateTime? DueDate          { get; set; } // date
		[Column(@"document_status_id"), Nullable            ] public int?      DocumentStatusId { get; set; } // int(11)
		[Column(@"add_date"),           Nullable            ] public DateTime? AddDate          { get; set; } // datetime
		[Column(@"add_by"),             Nullable            ] public string    AddBy            { get; set; } // varchar(100)
		[Column(@"edit_date"),          Nullable            ] public DateTime? EditDate         { get; set; } // datetime
		[Column(@"edit_by"),            Nullable            ] public string    EditBy           { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_grn_header_po_id_BackReference
		/// </summary>
		[Association(ThisKey="PurchaseOrderId", OtherKey="PoId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<GrnHeader> grnheaderpoids { get; set; }

		/// <summary>
		/// FK_po_details_po_purchase_order_id_BackReference
		/// </summary>
		[Association(ThisKey="PurchaseOrderId", OtherKey="PoId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PurchaseOrderDetails> podetailspopurchaseorderids { get; set; }

		/// <summary>
		/// FK_po_ms_aktor_aktor_id
		/// </summary>
		[Association(ThisKey="ProdusenId", OtherKey="AktorId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_po_ms_aktor_aktor_id", BackReferenceName="pomsaktoraktorids")]
		public MsAktor pomsaktoraktorid { get; set; }

		/// <summary>
		/// FK_po_pr_purchase_requisition_id
		/// </summary>
		[Association(ThisKey="PrId", OtherKey="PurchaseRequisitionId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_po_pr_purchase_requisition_id", BackReferenceName="poprpurchaserequisitionids")]
		public PurchaseRequisition poprpurchaserequisitionid { get; set; }

		#endregion
	}

	[Table("purchase_requisition")]
	public partial class PurchaseRequisition
	{
		[Column(@"purchase_requisition_id"), PrimaryKey, Identity] public int       PurchaseRequisitionId { get; set; } // int(11)
		[Column(@"aktor_id"),                Nullable            ] public int?      AktorId               { get; set; } // int(11)
		[Column(@"kode"),                    Nullable            ] public string    Kode                  { get; set; } // varchar(30)
		[Column(@"released_date"),           Nullable            ] public DateTime? ReleasedDate          { get; set; } // date
		[Column(@"need_time"),               Nullable            ] public DateTime? NeedTime              { get; set; } // date
		[Column(@"document_status_id"),      Nullable            ] public int?      DocumentStatusId      { get; set; } // int(11)
		[Column(@"remark"),                  Nullable            ] public string    Remark                { get; set; } // varchar(255)
		[Column(@"add_date"),                Nullable            ] public DateTime? AddDate               { get; set; } // datetime
		[Column(@"add_by"),                  Nullable            ] public string    AddBy                 { get; set; } // varchar(100)
		[Column(@"edit_date"),               Nullable            ] public DateTime? EditDate              { get; set; } // datetime
		[Column(@"edit_by"),                 Nullable            ] public string    EditBy                { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_po_pr_purchase_requisition_id_BackReference
		/// </summary>
		[Association(ThisKey="PurchaseRequisitionId", OtherKey="PrId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PurchaseOrders> poprpurchaserequisitionids { get; set; }

		/// <summary>
		/// FK_pr_details_purchase_requisition_pr_id_BackReference
		/// </summary>
		[Association(ThisKey="PurchaseRequisitionId", OtherKey="PurchaseRequisitionId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PurchaseRequisitionDetails> prdetailspurchaserequisitionprids { get; set; }

		/// <summary>
		/// FK_purchase_requisition_ms_aktor_aktor_id
		/// </summary>
		[Association(ThisKey="AktorId", OtherKey="AktorId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_purchase_requisition_ms_aktor_aktor_id", BackReferenceName="purchaserequisitionmsaktoraktorids")]
		public MsAktor purchaserequisitionmsaktoraktorid { get; set; }

		#endregion
	}

	[Table("purchase_requisition_details")]
	public partial class PurchaseRequisitionDetails
	{
		[Column(@"pr_details_id"),           PrimaryKey,  Identity] public int       PrDetailsId           { get; set; } // int(11)
		[Column(@"purchase_requisition_id"), NotNull              ] public int       PurchaseRequisitionId { get; set; } // int(11)
		[Column(@"pupuk_id"),                NotNull              ] public int       PupukId               { get; set; } // int(11)
		[Column(@"qty"),                     NotNull              ] public int       Qty                   { get; set; } // int(11)
		[Column(@"add_date"),                   Nullable          ] public DateTime? AddDate               { get; set; } // datetime
		[Column(@"add_by"),                     Nullable          ] public string    AddBy                 { get; set; } // varchar(100)
		[Column(@"edit_date"),                  Nullable          ] public DateTime? EditDate              { get; set; } // datetime
		[Column(@"edit_by"),                    Nullable          ] public string    EditBy                { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_pr_details_ms_pupuk_pupuk_id
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_pr_details_ms_pupuk_pupuk_id", BackReferenceName="prdetailsmspupukpupukids")]
		public MsPupuk prdetailsmspupukpupukid { get; set; }

		/// <summary>
		/// FK_pr_details_purchase_requisition_pr_id
		/// </summary>
		[Association(ThisKey="PurchaseRequisitionId", OtherKey="PurchaseRequisitionId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_pr_details_purchase_requisition_pr_id", BackReferenceName="prdetailspurchaserequisitionprids")]
		public PurchaseRequisition prdetailspurchaserequisitionprid { get; set; }

		#endregion
	}

	[Table("refarea")]
	public partial class Refarea
	{
		[PrimaryKey, Identity] public int    RefAreaId { get; set; } // int(11)
		[Column,     Nullable] public string KodeArea  { get; set; } // varchar(10)
		[Column,     Nullable] public string NamaArea  { get; set; } // varchar(50)
		[Column,     Nullable] public int?   KotaId    { get; set; } // int(11)
	}

	[Table("refkota")]
	public partial class Refkota
	{
		[PrimaryKey, Identity] public int    RefKotaId  { get; set; } // int(11)
		[Column,     Nullable] public string Kode       { get; set; } // varchar(10)
		[Column,     Nullable] public string Nama       { get; set; } // varchar(50)
		[Column,     Nullable] public int?   ProvinsiId { get; set; } // int(11)
	}

	[Table("refnegara")]
	public partial class Refnegara
	{
		[PrimaryKey, Identity   ] public int    RefNegaraId  { get; set; } // int(11)
		[Column,     NotNull    ] public string Nama         { get; set; } // varchar(50)
		[Column,        Nullable] public string Deskripsi    { get; set; } // varchar(100)
		[Column,        Nullable] public string KodeISO      { get; set; } // varchar(3)
		[Column,        Nullable] public string KodeMataUang { get; set; } // varchar(5)
	}

	[Table("refprovinsi")]
	public partial class Refprovinsi
	{
		[PrimaryKey, Identity   ] public int    RefProvinsiId { get; set; } // int(11)
		[Column,     NotNull    ] public int    NegaraId      { get; set; } // int(11)
		[Column,     NotNull    ] public string Nama          { get; set; } // varchar(50)
		[Column,        Nullable] public string Kode          { get; set; } // varchar(50)
	}

	[Table("role")]
	public partial class Role
	{
		[Column(@"role_id"),   PrimaryKey, Identity] public int       RoleId   { get; set; } // int(11)
		[Column(@"nama"),      Nullable            ] public string    Nama     { get; set; } // varchar(100)
		[Column(@"add_date"),  Nullable            ] public DateTime? AddDate  { get; set; } // datetime
		[Column(@"add_by"),    Nullable            ] public string    AddBy    { get; set; } // varchar(100)
		[Column(@"edit_date"), Nullable            ] public DateTime? EditDate { get; set; } // datetime
		[Column(@"edit_by"),   Nullable            ] public string    EditBy   { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_ms_aktor_role_role_id_BackReference
		/// </summary>
		[Association(ThisKey="RoleId", OtherKey="RoleId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MsAktor> msaktorids { get; set; }

		#endregion
	}

	[Table("sequence_numbers")]
	public partial class SequenceNumbers
	{
		[Column(@"sequence_number_id"), PrimaryKey,  Identity] public int       SequenceNumberId { get; set; } // int(11)
		[Column(),                      NotNull              ] public int       Nilai            { get; set; } // int(11)
		[Column(),                         Nullable          ] public DateTime? Date             { get; set; } // date
		[Column(),                         Nullable          ] public string    FormatKode       { get; set; } // varchar(20)
		[Column(),                         Nullable          ] public string    Deskripsi        { get; set; } // varchar(100)
	}

	[Table("static_data")]
	public partial class StaticData
	{
		[Column(@"static_data_id"), PrimaryKey,  Identity] public int       StaticDataId { get; set; } // int(11)
		[Column(@"section"),           Nullable          ] public int?      Section      { get; set; } // int(4)
		[Column(@"kode"),              Nullable          ] public string    Kode         { get; set; } // varchar(50)
		[Column(@"nama"),              Nullable          ] public string    Nama         { get; set; } // varchar(100)
		[Column(@"is_delete"),      NotNull              ] public ulong     IsDelete     { get; set; } // bit(1)
		[Column(@"add_date"),          Nullable          ] public DateTime? AddDate      { get; set; } // datetime
		[Column(@"add_by"),            Nullable          ] public string    AddBy        { get; set; } // varchar(100)
		[Column(@"edit_date"),         Nullable          ] public DateTime? EditDate     { get; set; } // datetime
		[Column(@"edit_by"),           Nullable          ] public string    EditBy       { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_ms_pupuk_carapelepasan_staticdata_BackReference
		/// </summary>
		[Association(ThisKey="StaticDataId", OtherKey="CaraPelepasanId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MsPupuk> mspupukcarapelepasanstaticdatas { get; set; }

		/// <summary>
		/// FK_ms_pupuk_static_data_bentuk_pupuk_id_BackReference
		/// </summary>
		[Association(ThisKey="StaticDataId", OtherKey="BentukPupukId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MsPupuk> mspupukstaticdatabentukpupukids { get; set; }

		/// <summary>
		/// FK_ms_pupuk_static_data_cara_pakai_id_BackReference
		/// </summary>
		[Association(ThisKey="StaticDataId", OtherKey="CaraPakaiId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MsPupuk> mspupukstaticdatacarapakaiids { get; set; }

		/// <summary>
		/// FK_ms_pupuk_static_data_jenis_unsur_id_BackReference
		/// </summary>
		[Association(ThisKey="StaticDataId", OtherKey="JenisUnsurId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MsPupuk> mspupukstaticdatajenisunsurids { get; set; }

		/// <summary>
		/// FK_ms_pupuk_static_data_sumber_pupuk_id_BackReference
		/// </summary>
		[Association(ThisKey="StaticDataId", OtherKey="SumberPupukId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MsPupuk> mspupukstaticdatasumberpupukids { get; set; }

		#endregion
	}

	[Table("stores")]
	public partial class Store
	{
		[Column(@"store_id"),       PrimaryKey,  Identity] public int       StoreId       { get; set; } // int(11)
		[Column(@"distributor_id"),    Nullable          ] public int?      DistributorId { get; set; } // int(11)
		[Column(@"kode"),              Nullable          ] public string    Kode          { get; set; } // varchar(15)
		[Column(@"nama"),              Nullable          ] public string    Nama          { get; set; } // varchar(100)
		[Column(@"is_delete"),      NotNull              ] public ulong     IsDelete      { get; set; } // bit(1)
		[Column(@"add_date"),          Nullable          ] public DateTime? AddDate       { get; set; } // datetime
		[Column(@"add_by"),            Nullable          ] public string    AddBy         { get; set; } // varchar(100)
		[Column(@"edit_date"),         Nullable          ] public DateTime? EditDate      { get; set; } // datetime
		[Column(@"edit_by"),           Nullable          ] public string    EditBy        { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_stores_ms_aktor_aktor_id
		/// </summary>
		[Association(ThisKey="DistributorId", OtherKey="AktorId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_stores_ms_aktor_aktor_id", BackReferenceName="storesmsaktoraktorids")]
		public MsAktor msaktoraktorid { get; set; }

		/// <summary>
		/// FK_pupuk_stores_stores_store_id_BackReference
		/// </summary>
		[Association(ThisKey="StoreId", OtherKey="StoreId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<PupukStores> pupukstoreids { get; set; }

		#endregion
	}

	[Table("transactions")]
	public partial class Transaction
	{
		[Column(@"transaction_id"), PrimaryKey, Identity] public int       TransactionId { get; set; } // int(11)
		[Column(@"petani_id"),      Nullable            ] public int?      PetaniId      { get; set; } // int(11)
		[Column(@"pupuk_id"),       Nullable            ] public int?      PupukId       { get; set; } // int(11)
		[Column(@"nama"),           Nullable            ] public string    Nama          { get; set; } // varchar(255)
		[Column(@"qty"),            Nullable            ] public int?      Qty           { get; set; } // int(11)
		[Column(@"harga"),          Nullable            ] public decimal?  Harga         { get; set; } // decimal(18,2)
		[Column(@"store_id"),       Nullable            ] public int?      StoreId       { get; set; } // int(11)
		[Column(@"add_date"),       Nullable            ] public DateTime? AddDate       { get; set; } // datetime
		[Column(@"add_by"),         Nullable            ] public string    AddBy         { get; set; } // varchar(100)
		[Column(@"edit_date"),      Nullable            ] public DateTime? EditDate      { get; set; } // datetime
		[Column(@"edit_by"),        Nullable            ] public string    EditBy        { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_transactions_ms_aktor_aktor_id
		/// </summary>
		[Association(ThisKey="PetaniId", OtherKey="AktorId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_transactions_ms_aktor_aktor_id", BackReferenceName="transactionsmsaktoraktorids")]
		public MsAktor msaktoraktorid { get; set; }

		/// <summary>
		/// FK_transactions_ms_pupuk_pupuk_id
		/// </summary>
		[Association(ThisKey="PupukId", OtherKey="PupukId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_transactions_ms_pupuk_pupuk_id", BackReferenceName="transactionsmspupukpupukids")]
		public MsPupuk mspupukpupukid { get; set; }

		/// <summary>
		/// FK_transaction_bill_rels_transactions_transaction_id_BackReference
		/// </summary>
		[Association(ThisKey="TransactionId", OtherKey="TransactionId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<TransactionBillRels> transactionbillrelstransactionids { get; set; }

		#endregion
	}

	[Table("transaction_bill_rels")]
	public partial class TransactionBillRels
	{
		[Column(@"transaction_bill_rel_id"), PrimaryKey,  Identity] public int       TransactionBillRelId { get; set; } // int(11)
		[Column(@"transaction_id"),             Nullable          ] public int?      TransactionId        { get; set; } // int(11)
		[Column(@"billing_id"),                 Nullable          ] public int?      BillingId            { get; set; } // int(11)
		[Column(@"is_delete"),               NotNull              ] public ulong     IsDelete             { get; set; } // bit(1)
		[Column(@"add_date"),                   Nullable          ] public DateTime? AddDate              { get; set; } // datetime
		[Column(@"add_by"),                     Nullable          ] public string    AddBy                { get; set; } // varchar(100)
		[Column(@"edit_date"),                  Nullable          ] public DateTime? EditDate             { get; set; } // datetime
		[Column(@"edit_by"),                    Nullable          ] public string    EditBy               { get; set; } // varchar(100)

		#region Associations

		/// <summary>
		/// FK_transaction_bill_rels_billings_billing_id
		/// </summary>
		[Association(ThisKey="BillingId", OtherKey="BillingId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_transaction_bill_rels_billings_billing_id", BackReferenceName="transactionbillrelsbillingids")]
		public Billing transactionbillrelsbillingsbillingid { get; set; }

		/// <summary>
		/// FK_transaction_bill_rels_transactions_transaction_id
		/// </summary>
		[Association(ThisKey="TransactionId", OtherKey="TransactionId", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_transaction_bill_rels_transactions_transaction_id", BackReferenceName="transactionbillrelstransactionids")]
		public Transaction transactionbillrelstransactionstransactionid { get; set; }

		#endregion
	}

	[Table("users")]
	public partial class User
	{
		[Column(@"user_id"),   PrimaryKey,  Identity] public int       UserId   { get; set; } // int(11)
		[Column(@"aktor_id"),  NotNull              ] public int       AktorId  { get; set; } // int(11)
		[Column(@"username"),  NotNull              ] public string    Username { get; set; } // varchar(100)
		[Column(@"password"),  NotNull              ] public string    Password { get; set; } // varchar(100)
		[Column(@"add_date"),     Nullable          ] public DateTime? AddDate  { get; set; } // datetime
		[Column(@"add_by"),       Nullable          ] public string    AddBy    { get; set; } // varchar(100)
		[Column(@"edit_date"),    Nullable          ] public DateTime? EditDate { get; set; } // datetime
		[Column(@"edit_by"),      Nullable          ] public string    EditBy   { get; set; } // varchar(100)
		[Column(@"is_delete"), NotNull              ] public ulong     IsDelete { get; set; } // bit(1)

		#region Associations

		/// <summary>
		/// FK_users_ms_aktor_aktor_id
		/// </summary>
		[Association(ThisKey="AktorId", OtherKey="AktorId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_users_ms_aktor_aktor_id", BackReferenceName="usersmsaktoraktorids")]
		public MsAktor msaktoraktorid { get; set; }

		#endregion
	}

	[Table("vlogin", IsView=true)]
	public partial class Vlogin
	{
		[Column, NotNull    ] public string Username  { get; set; } // varchar(100)
		[Column, NotNull    ] public string Password  { get; set; } // varchar(100)
		[Column, NotNull    ] public int    AktorId   { get; set; } // int(11)
		[Column, NotNull    ] public int    RoleId    { get; set; } // int(11)
		[Column,    Nullable] public string RoleName  { get; set; } // varchar(100)
		[Column,    Nullable] public string NamaAktor { get; set; } // varchar(100)
		[Column,    Nullable] public string Email     { get; set; } // varchar(100)
	}

	public static partial class TableExtensions
	{
		public static Billing Find(this ITable<Billing> table, int BillingId)
		{
			return table.FirstOrDefault(t =>
				t.BillingId == BillingId);
		}

		public static GrnDetails Find(this ITable<GrnDetails> table, int GrnDetailId)
		{
			return table.FirstOrDefault(t =>
				t.GrnDetailId == GrnDetailId);
		}

		public static GrnHeader Find(this ITable<GrnHeader> table, int GrnHeaderId)
		{
			return table.FirstOrDefault(t =>
				t.GrnHeaderId == GrnHeaderId);
		}

		public static MsAktor Find(this ITable<MsAktor> table, int AktorId)
		{
			return table.FirstOrDefault(t =>
				t.AktorId == AktorId);
		}

		public static MsPupuk Find(this ITable<MsPupuk> table, int PupukId)
		{
			return table.FirstOrDefault(t =>
				t.PupukId == PupukId);
		}

		public static Payment Find(this ITable<Payment> table, int PaymentId)
		{
			return table.FirstOrDefault(t =>
				t.PaymentId == PaymentId);
		}

		public static PupukStocks Find(this ITable<PupukStocks> table, int PupukStockId)
		{
			return table.FirstOrDefault(t =>
				t.PupukStockId == PupukStockId);
		}

		public static PupukStores Find(this ITable<PupukStores> table, int PupukStoreId)
		{
			return table.FirstOrDefault(t =>
				t.PupukStoreId == PupukStoreId);
		}

		public static PurchaseOrderDetails Find(this ITable<PurchaseOrderDetails> table, int PoDetailsId)
		{
			return table.FirstOrDefault(t =>
				t.PoDetailsId == PoDetailsId);
		}

		public static PurchaseOrders Find(this ITable<PurchaseOrders> table, int PurchaseOrderId)
		{
			return table.FirstOrDefault(t =>
				t.PurchaseOrderId == PurchaseOrderId);
		}

		public static PurchaseRequisition Find(this ITable<PurchaseRequisition> table, int PurchaseRequisitionId)
		{
			return table.FirstOrDefault(t =>
				t.PurchaseRequisitionId == PurchaseRequisitionId);
		}

		public static PurchaseRequisitionDetails Find(this ITable<PurchaseRequisitionDetails> table, int PrDetailsId)
		{
			return table.FirstOrDefault(t =>
				t.PrDetailsId == PrDetailsId);
		}

		public static Refarea Find(this ITable<Refarea> table, int RefAreaId)
		{
			return table.FirstOrDefault(t =>
				t.RefAreaId == RefAreaId);
		}

		public static Refkota Find(this ITable<Refkota> table, int RefKotaId)
		{
			return table.FirstOrDefault(t =>
				t.RefKotaId == RefKotaId);
		}

		public static Refnegara Find(this ITable<Refnegara> table, int RefNegaraId)
		{
			return table.FirstOrDefault(t =>
				t.RefNegaraId == RefNegaraId);
		}

		public static Refprovinsi Find(this ITable<Refprovinsi> table, int RefProvinsiId)
		{
			return table.FirstOrDefault(t =>
				t.RefProvinsiId == RefProvinsiId);
		}

		public static Role Find(this ITable<Role> table, int RoleId)
		{
			return table.FirstOrDefault(t =>
				t.RoleId == RoleId);
		}

		public static SequenceNumbers Find(this ITable<SequenceNumbers> table, int SequenceNumberId)
		{
			return table.FirstOrDefault(t =>
				t.SequenceNumberId == SequenceNumberId);
		}

		public static StaticData Find(this ITable<StaticData> table, int StaticDataId)
		{
			return table.FirstOrDefault(t =>
				t.StaticDataId == StaticDataId);
		}

		public static Store Find(this ITable<Store> table, int StoreId)
		{
			return table.FirstOrDefault(t =>
				t.StoreId == StoreId);
		}

		public static Transaction Find(this ITable<Transaction> table, int TransactionId)
		{
			return table.FirstOrDefault(t =>
				t.TransactionId == TransactionId);
		}

		public static TransactionBillRels Find(this ITable<TransactionBillRels> table, int TransactionBillRelId)
		{
			return table.FirstOrDefault(t =>
				t.TransactionBillRelId == TransactionBillRelId);
		}

		public static User Find(this ITable<User> table, int UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}
	}
}
